### ISSUE TITLE
Failed to upload

### ISSUE THREAD

**Issue by chetankatke** [out386/aria-telegram-mirror-bot#1]
It sends msg that failed to upload ******** to drive.Error: invalid_request

**Comment by out386** [comment]
Did you set up the bot according to the new instructions I pushed recently? If yes, try deleting both the .json files in the bot directory, and try uploading again.

Also, check that the Drive API is enabled in the account you're using.

**Comment by chetankatke** [comment]
I set up bot with recent commit. it was working properly earlier. but giving this error now.

**Comment by chetankatke** [comment]
Deleting both .json and authorizing again solved the issue .thanks

**Comment by out386** [comment]
Awesome.

**Comment by arvs47** [comment]
hello  a noob question , 
 ,i just want to know is it possible to make this script in google app script and download the files directly to google drive , with the help of google app script , i have seen some videos that can add details to the google sheets from telegram using google app script , so is there any chances to convert this script to a google app script and do the download directly to google drive , saw some scripts which can download files from urls to google drive using the google app script ,,
