### ISSUE TITLE
No constant.js file 

### ISSUE THREAD

**Issue by begginer-123** [out386/aria-telegram-mirror-bot#112]
![Screenshot_2020-06-04-08-44-59-504_com termux](https://user-images.githubusercontent.com/66400864/83711946-3ece9600-a642-11ea-9a1a-82cd79cda232.jpg)
Any help

**Comment by out386** [comment]
Thanks to bad decisions, it's a hidden file. Use `ls -a` to see it.
Also, `cp src/.constants.js.example src/.constants.js`

**Comment by begginer-123** [comment]
Thank You for the fast reply

**Comment by begginer-123** [comment]
> Thanks to bad decisions, it's a hidden file. Use `ls -a` to see it.
> Also, `cp src/.constants.js.example src/.constants.js`

I am having trouble deploying this google cloud. Is there a small tutorial for gc?
Or you can breifly tell what to do.

**Comment by out386** [comment]
@begginer-123, same steps for Compute Engine. Start a VPS, and follow the readme.

**Comment by begginer-123** [comment]
> @begginer-123, same steps for Compute Engine. Start a VPS, and follow the readme.

Any os recommadation for vps
