### ISSUE TITLE
A2c failed to open websocket

### ISSUE THREAD

**Issue by RAHUL112KAPOOR** [out386/aria-telegram-mirror-bot#124]
root@localhost:~/aria-telegram-mirror-bot# ./aria.sh
Aria2c daemon started
root@localhost:~/aria-telegram-mirror-bot# npm start

> mirror-bot@2.0.0 start /root/aria-telegram-mirror-bot
> NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js

A2C: Failed to open websocket. Run aria.sh first. Exiting.
root@localhost:~/aria-telegram-mirror-bot#

**Comment by out386** [comment]
Run `./aria.sh` first.
