### ISSUE TITLE
tsc error

### ISSUE THREAD

**Issue by hypercian** [out386/aria-telegram-mirror-bot#125]
Hi
I have this errors while tsc

![Screenshot (627)](https://user-images.githubusercontent.com/62615412/103147658-b7c34580-476c-11eb-8e9b-f33c271357e5.png)

**Comment by arghyac35** [comment]
`npm i -g typescript@4.0.3`, use this typescript version, newer TS version throws this error due to some changes in promise.

I have fixed it [here](https://github.com/arghyac35/aria-telegram-mirror-bot/commit/5f781127341fd6968b60f09436e1a8bcd7e3642b)

**Comment by out386** [comment]
@arghyac35, thanks. Fixed in 9acb4d.
Also, just switched to using npx in c68f0e, so no need to install typescript globally anymore, 'cause why not?
