### ISSUE TITLE
no response fromserver when i input url in bot

### ISSUE THREAD

**Issue by destroyer19991** [out386/aria-telegram-mirror-bot#14]
when i put url in bot its stuck at preparing and there is no response in terminal , tried many times still no help

**Comment by songotenks69** [comment]
Can you share the URL, because it's working fine for a lot of us

**Comment by destroyer19991** [comment]
bro stuck at authentication so its the readme.md url

**Comment by songotenks69** [comment]
Are you sure your constants and client secret are correct?

**Comment by destroyer19991** [comment]
yep

**Comment by out386** [comment]
Pull the new commits, `killall aria2c && ./aria.sh`, and try again.

**Comment by destroyer19991** [comment]
download:https://raw.githubusercontent.com/out386/aria-telegram-mirror-bot/master/README.md gid:3bebb4a86071dcb6
error 3bebb4a86071dcb6
cleanupDownload: deleting
now this

**Comment by out386** [comment]
Same happens for all files, not just Readme?

**Comment by destroyer19991** [comment]
i am still to authenticate bot

**Comment by out386** [comment]
You don't need Readme to authenticate it, just try something else.

**Comment by destroyer19991** [comment]
Same issue with all links

**Comment by out386** [comment]
Check the file permissions on the downloads directory - the bot should be able to write to it. Recheck your .constants - specifically the downloads directory constant.

**Comment by destroyer19991** [comment]
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. module.js:652:30
A2C: Websocket opened
Failure { code: 1, message: 'Unauthorized' }
cleanupDownload: deleting

**Comment by out386** [comment]
Your client secret is messed up.

**Comment by songotenks69** [comment]
Or there's a chance he put different keys in aria.sh and .constants.js (or
he's running two aria sessions)

**Comment by destroyer19991** [comment]
checked all, everything is fine still error
