### ISSUE TITLE
Website Phel

### ISSUE THREAD

**Issue by songotenks69** [out386/aria-telegram-mirror-bot#15]
When someone mirrors a website (e.g https://del.dog/d9pregj) the download doesn't start (no shit sherlock) but I am unable to mirror again until I restart the bot

**Comment by out386** [comment]
Okay, fixed in 4ab73787

**Comment by songotenks69** [comment]
Well it's fixed but now unable to mirror .torrent files (e.g. ```https://psarips.net/torrents/2019/03/The.Grand.Tour.S03E11.Sea.to.Unsalty.Sea.1080p.WEBRip.6CH.x265.HEVC-PSA-278886.torrent```)

It gives

Upload failed. Could not get files.

**Comment by songotenks69** [comment]
```start ef6e30cc1ebff0ce
download:https://psarips.net/torrents/2019/03/The.Grand.Tour.S03E11.Sea.to.Unsalty.Sea.1080p.WEBRip.6CH.x265.HEVC-PSA-278886.torrent gid:ef6e30cc1ebff0ce
start c4c6bca3e9a6ca39
onDownloadComplete: No files
cleanupDownload: deleting```

**Comment by chetankatke** [comment]
@songotenks69 it's working fine

**Comment by out386** [comment]
@songotenks69, oh yeah. Will fix that.

**Comment by chetankatke** [comment]
Sorry it's not working after I did git pull origin master

**Comment by songotenks69** [comment]
Works good (till now 👀)
