### ISSUE TITLE
Polling Issue Continued

### ISSUE THREAD

**Issue by Rajwadkar07** [out386/aria-telegram-mirror-bot#19]
I have not started any other bot instance. Still I am facing this error. Any way I can stop all t
he instances?

**Comment by out386** [comment]
Try revoking the token from Botfather.

**Comment by Rajwadkar07** [comment]
I tried that, didn't work

**Comment by out386** [comment]
You mentioned on your other issue that you were running this on Heroku? Try it locally and see if you get the same problem.
Then make a new bot in Botfather, and try its token.

**Comment by Rajwadkar07** [comment]
okay sure. I'll report to you.

**Comment by Rajwadkar07** [comment]
creating a new account helped me to do it on web console and the file was uploaded successfully but now when I deployed the app its asking for authentication code and gave URL in logs. But no place where I can paste it. Also as it is uploading it cannot be cancelled and on using web console again gives me polling error. So is there a way I ca stop the uploads and stop the polling errors too. Thanks!

**Comment by out386** [comment]
Well, Heroku isn't supported. This project isn't meant for serverless. So I can't help you with that.

**Comment by songotenks69** [comment]
LMAO

**Comment by songotenks69** [comment]
Run it locally and push the credentials ez
