### ISSUE TITLE
everytime i try to setup bot this issue appears

### ISSUE THREAD

**Issue by destroyer19991** [out386/aria-telegram-mirror-bot#23]
is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. module.js:652:30
A2C: Websocket opened
download:https://raw.githubusercontent.com/out386/aria-telegram-mirror-bot/master/README.md gid:a91573934c846ba3
start a91573934c846ba3
error a91573934c846ba3
cleanupDownload: deleting
download:https://a.uguu.se/A5V8pixUxJ_client_secret.json gid:112d173517308acb
start 112d173517308acb
error 112d173517308acb
cleanupDownload: deleting

**Comment by noobvishal** [comment]
Same here
I even set the environment variable NTBA_FIX_319 to 1
But it still has the cleanup download: Deleting
