### ISSUE TITLE
unable to start bot

### ISSUE THREAD

**Issue by chetankatke** [out386/aria-telegram-mirror-bot#35]
auto delete msg feature of bot not letting me to start the bot

**Comment by out386** [comment]
What do you mean? What is it doing? Elaborate, please.

**Comment by chetankatke** [comment]
When I press start bot starts then after few seconds it deletes the start msg and start button reappear

**Comment by chetankatke** [comment]
Tell me solution please

**Comment by out386** [comment]
Just pull from master. It's fixed now.

**Comment by chetankatke** [comment]
Thanks man
