### ISSUE TITLE
Can you please add heroku support ?

### ISSUE THREAD

**Issue by rsoorajs** [out386/aria-telegram-mirror-bot#40]
Can you please add heroku support,by providing heroku deploy button ? it may help for beginners. 

Thank you

**Comment by out386** [comment]
@PainKiller3 did this : https://github.com/PainKiller3/aria-telegram-mirror-bot/commit/2b9b4d3ed3db7774fb2f0d85fb45dfe20ec2dec9

I haven't picked the commit because I haven't tested it yet.
