### ISSUE TITLE
Blocked Torrent Sites

### ISSUE THREAD

**Issue by usmanmughalji** [out386/aria-telegram-mirror-bot#41]
['yts', 'YTS', 'cruzing.xyz', 'eztv.ag', 'YIFY'], // Prevent downloading from URLs containing these substrings

Why these sites are blocked means these strings or name is there any specific reason, if i want to download anything from these torrent sites.

**Comment by out386** [comment]
Relevant section from the README:
`ARIA_FILTERED_DOMAINS: The bot will refuse to download files from these domains. Can be an empty list.`

**Comment by usmanmughalji** [comment]
Thanks.
