### ISSUE TITLE
Dir Failed

### ISSUE THREAD

**Issue by deadlyghost088** [out386/aria-telegram-mirror-bot#42]
I tried setting up everything from the README but I'm still getting this error for some reason. I tried changing the download directory in constants.js but same error.

> A2C: Websocket opened. Bot ready.
> download:https://raw.githubusercontent.com/out386/aria-telegram-mirror-bot/master/README.md gid:765a80751222be8d
> Started 765a80751222be8d. Dir: 0c10a633-5b6d-404a-a4f0-74604c138a6b.
> 765a80751222be8d failed. Download aborted.
> cleanup: Deleted 0c10a633-5b6d-404a-a4f0-74604c138a6b
> 
> download:https://raw.githubusercontent.com/out386/aria-telegram-mirror-bot/master/README.md gid:45ec985705c9ea33
> Started 45ec985705c9ea33. Dir: f83ce242-a223-4979-a7e0-b4b62ebe30f9.
> 45ec985705c9ea33 failed. Download aborted.
> cleanup: Deleted f83ce242-a223-4979-a7e0-b4b62ebe30f9

**Comment by out386** [comment]
1) Make sure you aren't running out of space
2) Make sure that the bot can write to your download dir. Check directory permissions, and it should be owned by the user the bot is running under.

**Comment by deadlyghost088** [comment]
Thanks for replying so soon!
I figured out the issue *dumb me*: the download directory in constants.js was set up wrong. I corrected it and the bot started working!
