### ISSUE TITLE
Using Bot name

### ISSUE THREAD

**Issue by foxcornlab** [out386/aria-telegram-mirror-bot#44]
Bot isn't responding /mirror cmd if COMMANDS_USE_BOT_NAME: is kept true. If it's kept for false it will not respond of other cmd default by telegram.. So its better to make /mirror too not to have username after the command.. Thank you.. hope you got it!

**Comment by out386** [comment]
The __only__ function of `COMMANDS_USE_BOT_NAME ` is to make you address the bot by its username. Setting it to false will let you use `/mirror`. If you want to use commands from Telegram's suggestions, you have to set it to true. As most of the commands take parameters anyway, what you suggest is counterintuitive.
This is intended behavior.
Long pressing the Telegram suggestion on the mobile client will fill out the `/mirror@botname` for you. That doesn't work in the desktop client, though.
