### ISSUE TITLE
need help 

### ISSUE THREAD

**Issue by bodoamat-git** [out386/aria-telegram-mirror-bot#56]
after run **npm --max_old_space_size=128 start** i got this

run in : **windows 10** 

`C:\Users\user\Downloads\PHYTON\aria-telegram-mirror-bot>npm --max_old_space_size=128 start

> mirror-bot@1.1.0 start C:\Users\user\Downloads\PHYTON\aria-telegram-mirror-bot
> NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js

'NTBA_FIX_319' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mirror-bot@1.1.0 start: `NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mirror-bot@1.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-10-14T11_38_01_279Z-debug.log

C:\Users\user\Downloads\PHYTON\aria-telegram-mirror-bot>`

**Comment by out386** [comment]
I haven't tested the bot on windows. Try this anyway:
In https://github.com/out386/aria-telegram-mirror-bot/blob/master/package.json#7, line 7, replace `NTBA_FIX_319=1` with `set NTBA_FIX_319=1`.

**Comment by bodoamat-git** [comment]
okay work now .. thanks
