### ISSUE TITLE
ECONNREFUSED on Termux

### ISSUE THREAD

**Issue by A-LoneWolf** [out386/aria-telegram-mirror-bot#61]
Hii I am just new to this and Tried to delpoy this mirror bot I am using Termux and do all the steps as written and when I Do a mirror command on bot getting this error attached screen shot.
![Screenshot_20191101-152957](https://user-images.githubusercontent.com/54808110/68017495-da6ae300-fcbc-11e9-8d7b-7a7d4bc4cb93.png)
![Screenshot_20191101-153321](https://user-images.githubusercontent.com/54808110/68017532-f53d5780-fcbc-11e9-8a8d-a66ebd7f0e55.png)

**Comment by out386** [comment]
Did you start the aria2 daemon with .aria.sh?
Also, try changing the port to an even higher number, both in .constants.js and in .aria.sh.
And make sure that your aria secret is correct.

**Comment by A-LoneWolf** [comment]
Yes My secret is correct, I have started aria2 daemon, could you suggest port please.

**Comment by a092devs** [comment]
> Yes My secret is correct, I have started aria2 daemon, could you suggest port please.

Try 6800 once

**Comment by A-LoneWolf** [comment]
I have tried 6800 and got this error

**Comment by A-LoneWolf** [comment]
I have tried 6800 port and got this error bro check screenshots I am using termux and I think I should deploy this to some where like heroku could you tell me how to deploy to heroku
![Screenshot_20191102-142113](https://user-images.githubusercontent.com/54808110/68068609-95a68100-fd7c-11e9-850f-d4d34b8649ad.png)
![Screenshot_20191102-142218](https://user-images.githubusercontent.com/54808110/68068612-9a6b3500-fd7c-11e9-87cc-6f76c9a51167.png)
![Screenshot_20191102-142229](https://user-images.githubusercontent.com/54808110/68068615-9e975280-fd7c-11e9-83ab-82862a2e5641.png)

**Comment by out386** [comment]
This last error is because you didn't configure the path correctly. In `src/.constants.js`, change `ARIA_DOWNLOAD_LOCATION` to point to something the bot can write to. Like a directory on `/sdcard/`

**Comment by A-LoneWolf** [comment]
Thank you so much now its working .. One last question where I can host this for free
