### ISSUE TITLE
Permission Denied for deleting file once downloaded on to Drive.

### ISSUE THREAD

**Issue by ruchirshetye** [out386/aria-telegram-mirror-bot#66]
```
gid: 9d4f2def55660f5f download:https://raw.githubusercontent.com/out386/aria-telegram-mirror-bot/master/README.md
9d4f2def55660f5f: Started. Dir: 2efb4cb5-3df9-40b9-a2b9-d312aab9ac66.
9d4f2def55660f5f: Completed. Filename: README.md. Starting upload.
9d4f2def55660f5f: Uploaded 
**cleanup: Failed to delete 2efb4cb5-3df9-40b9-a2b9-d312aab9ac66: EACCES: permission denied, unlink '/data/2efb4cb5-3df9-40b9-a2b9-d312aab9ac66/README.md'**
```
Since it's unable to delete the files, the storage get filled pretty quickly.
I tried giving read and write access to the /data folder using the following command.

1) sudo chmod -R 777 "/data"

Let me know how can I solve this issue.

**Comment by out386** [comment]
Make sure that /data is owned by the same user as the one the bot is running under. If that is not possible, set default 777 permissions on /data. Check [this answer](https://unix.stackexchange.com/a/1315).

**Comment by ruchirshetye** [comment]
My bad. The bot was running under a different user. It's working now. Thanks.

**Comment by usmanmughalji** [comment]
> My bad. The bot was running under a different user. It's working now. Thanks.

how did you solved this issue i am facing same i even check everything my user id too.
