### ISSUE TITLE
Found 15 errors.

### ISSUE THREAD

**Issue by arjun4414** [out386/aria-telegram-mirror-bot#68]
`src/.constants.js:10:27 - error TS1136: Property assignment expected.

10   SUDO_USERS: [012, 345], @Drdangjr// Telegram user IDs. These users can use the bot in any chat.
                             ~

src/.constants.js:10:27 - error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option in your 'tsconfig' or 'jsconfig' to remove this warning.

10   SUDO_USERS: [012, 345], @Drdangjr// Telegram user IDs. These users can use the bot in any chat.
                             ~~~~~~~~~

src/.constants.js:10:36 - error TS1146: Declaration expected.

10   SUDO_USERS: [012, 345], @Drdangjr// Telegram user IDs. These users can use the bot in any chat.
                                      

src/.constants.js:12:28 - error TS1005: ';' expected.

12   STATUS_UPDATE_INTERVAL_MS: 12000, // A smaller number will update faster, but might cause rate limiting
                              ~

src/.constants.js:13:21 - error TS1005: ';' expected.

13   DRIVE_FILE_PRIVATE: {
                       ~

src/.constants.js:15:11 - error TS1005: ';' expected.

15     EMAILS: ['upadhyay.arjun02@gmail.com', 'upadhyayarjun7@gmail.com']
             ~

src/.constants.js:16:4 - error TS1128: Declaration or statement expected.

16   },
      ~

src/.constants.js:19:9 - error TS1005: ';' expected.

19     host: 'hostname.domain',
           ~

src/.constants.js:20:9 - error TS1005: ';' expected.

20     port: 80,
           ~

src/.constants.js:21:9 - error TS1005: ';' expected.

21     path: '/botNotify'
           ~

src/.constants.js:22:4 - error TS1128: Declaration or statement expected.

22   },
      ~

src/.constants.js:25:9 - error TS1005: ';' expected.

25     NAME: "@mama"
           ~

src/.constants.js:26:4 - error TS1128: Declaration or statement expected.

26   },
      ~

src/.constants.js:28:1 - error TS1128: Declaration or statement expected.

28 });
   ~

src/.constants.js:28:2 - error TS1128: Declaration or statement expected.

28 });
    ~


Found 15 errors.
`

**Comment by gotenksIN** [comment]
All the errors are pretty explanatory 
You've filled the .constants.js wrong

**Comment by out386** [comment]
Like @gotenksIN said, you need the user ID, not your username. As mentioned [here](https://stackoverflow.com/a/32777943), to get the user ID:  
Send a message to your bot then retrieve the update with:  
`https://api.telegram.org/bot<TOKEN>/getUpdates`  
In the json string returned you will find your chat_id/user_id.

Put that ID inside those two lists where you put your username. And delete the two numbers already in there - those are examples.

**Comment by arjun4414** [comment]
@gotenksIN   can you help me in configure?

**Comment by out386** [comment]
If doing what I wrote above is confusing, send a message to [userinfobot](t.me/userinfobot) . It will send you your user ID.
In `SUDO_USERS`, delete `012, 345`, and replace it with your user ID. Delete the `@Drdangjr`.

**Comment by arjun4414** [comment]
done

**Comment by arjun4414** [comment]
after doing so 

src/.constants.js:11:3 - error TS1005: ':' expected.

11   AUTHORIZED_CHATS: [678, 901], // Telegram chat IDs. Anyone in these chats can use the bot.
     ~~~~~~~~~~~~~~~~

src/.constants.js:11:19 - error TS1005: ',' expected.

11   AUTHORIZED_CHATS: [678, 901], // Telegram chat IDs. Anyone in these chats can use the bot.
                     ~

src/.constants.js:11:31 - error TS1005: ':' expected.

11   AUTHORIZED_CHATS: [678, 901], // Telegram chat IDs. Anyone in these chats can use the bot.
                                 ~


Found 3 errors.

**Comment by out386** [comment]
You probably missed the `,` at the end of line 10

**Comment by arjun4414** [comment]
mirror-bot@2.0.0 start /Users/arjunupadhyay/aria-telegram-mirror-bot
> NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js

/Users/arjunupadhyay/aria-telegram-mirror-bot/out/.constants.js:14
        ENABLED: TRUE,
                 ^

ReferenceError: TRUE is not defined
    at Object.<anonymous> (/Users/arjunupadhyay/aria-telegram-mirror-bot/out/.constants.js:14:18)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/arjunupadhyay/aria-telegram-mirror-bot/out/download_tools/filename-utils.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/arjunupadhyay/aria-telegram-mirror-bot/out/download_tools/utils.js:4:23)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/arjunupadhyay/aria-telegram-mirror-bot/out/index.js:5:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mirror-bot@2.0.0 start: `NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mirror-bot@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/arjunupadhyay/.npm/_logs/2020-01-02T08_24_57_850Z-debug.log

**Comment by arjun4414** [comment]
for npm start

**Comment by arjun4414** [comment]
@out386

**Comment by out386** [comment]
It wasn't `TRUE`, it was `true`. Just delete `src/.constants.js` and start over.

**Comment by arjun4414** [comment]
aria2c: unrecognized option `--rpc-listen-axll=false'
Usage: aria2c [OPTIONS] [URI | MAGNET | TORRENT_FILE | METALINK_FILE]...
See 'aria2c -h'.
Aria2c daemon started



npm start

> mirror-bot@2.0.0 start /Users/arjunupadhyay/aria-telegram-mirror-bot
> NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js

A2C: Failed to open websocket. Run aria.sh first. Exiting.


i am getting this error

@out386

**Comment by gotenksIN** [comment]
can you just please read the error
you made a spelling mistake 
it should be `--rpc-listen-all=false`

**Comment by arjun4414** [comment]
Failed to download. Failed to make the directory /path/to/aria-telegram-mirror-bot/downloads (no trailing "/")/00abc390-2503-4896-898d-4ee374c7a3dc/Windows 10 X86 19H2 10in1 OEM pt-BR DEC 2019 {Gen2}/INFO, cause: Read-only file system


thanks the bot is on but when i download 
this is shown on every file\

**Comment by akhilnarang** [comment]
@arjun4414 read the readme, apply some logic, and try again. Otherwise please give up. Thanks!

**Comment by Techno-Disaster** [comment]
@arjun4414
please read it again.

**Comment by gotenksIN** [comment]
> Failed to download. Failed to make the directory /path/to/aria-telegram-mirror-bot/downloads (no trailing "/")/00abc390-2503-4896-898d-4ee374c7a3dc/Windows 10 X86 19H2 10in1 OEM pt-BR DEC 2019 {Gen2}/INFO, cause: Read-only file system
> 
> thanks the bot is on but when i download
> this is shown on every file\

read the error and guess why

**Comment by arjun4414** [comment]
sorry for all trouble but it is on !!!!!


thanks to all

**Comment by arjun4414** [comment]
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at fs.readFile (/root/aria-telegram-mirror-bot/out/drive/drive-auth.js:20:28)
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mirror-bot@2.0.0 start: `NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mirror-bot@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-06T04_30_55_365Z-debug.log




this is the error again i am getting please help me with this

**Comment by gotenksIN** [comment]
send the debug log as well, 
But my first suggestion is don't use a root account 
Make a normal user with sudo ( or don't give sudo, won't matter as long as packages are installed)
And make it download to a directory writable by the user

**Comment by out386** [comment]
> SyntaxError: Unexpected end of JSON input  
Fairly sure that you downloaded the wrong file from the Google Cloud Console and named it client_secret.json. The correct file will have "client_secret_" at the beginning of its name when you download it.  
Do that step again.
