### ISSUE TITLE
mirror-bot@1.0.0 No repository field.

### ISSUE THREAD

**Issue by pahapoika** [out386/aria-telegram-mirror-bot#7]
Hey.
I tried running the telegram bot, but npm gives following warning:
mirror-bot@1.0.0 No repository field.

and running npm start results following error:
https://pastebin.com/raw/E9EF6c4g

**Comment by out386** [comment]
You made mistakes while setting up your .constants.js.
Check it again, and fill it exactly like in the example. Don't delete any brackets or quotes.

**Comment by pahapoika** [comment]
The error is shown while doing npm install before I even configured .constants.js.

**Comment by pahapoika** [comment]
Oh it works even with the error. My bad
