### ISSUE TITLE
Doesn't upload: Get drive resumable url return invalid headers

### ISSUE THREAD

**Issue by inside83** [out386/aria-telegram-mirror-bot#70]
Hi
I need help resolving this issue. Progress bar working fine, file downloads and then I get this:
`Failed to upload debian-10.2.0-amd64-DVD-1.iso to Drive. Get drive resumable url return invalid headers: {
  "x-guploader-uploadid": "AEnB2UrHurd0MwwFdh_LNxc12uDwN1IfmoHjzz1J2COlqrIuLrjb6R-Y2oP7Ucb7sZmoXC0Lq14HLWV9PAwbwsl_ZJ3Sbrhvdritguc0OvnGS6DHkvuss0I",
  "vary": "Origin, X-Origin",
  "content-type": "application/json; charset=UTF-8",
  "content-length": "215",
  "date": "Fri, 17 Jan 2020 08:53:35 GMT",
  "server": "UploadServer",
  "alt-svc": "quic=\":443\"; ma=2592000; v=\"46,43\",h3-Q050=\":443\"; ma=2592000,h3-Q049=\":443\"; ma=2592000,h3-Q048=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000",
  "connection": "close"
}`
Tried it multiple time and every time it's content-length": "215".

**Comment by out386** [comment]
* Does this happen for all files? 
* Are you using Team Drives?
* Are you sure that you have permission to upload to that folder?

**Comment by inside83** [comment]
First off, thank you for your swift reply.

And yes on all three.

It was working fine yesterday.
I just deleted 
/opt/aria-telegram-mirror-bot/out/ directory
client_secret.json and
credentials.json files

Downloaded fresh client_secret.json, ran tsc, tried downloading readme file, got the link, authorized it, coped the code in terminal and I got this again
`Token stored to ./credentials.json
5c2771a58b34bdd0: Failed to upload - /opt/aria-telegram-mirror-bot/downloads/9b36f0f4-3e70-4b81-b8f5-5e412cd67a0b/README.md: Get drive resumable url return invalid headers: {
  "x-guploader-uploadid": "AEnB2UrT7llnyjX7DLB9q3b972sGeu156eMQYxvjaO-TeZM-NcwtzzdBOF7yWpn58O6r3BW4cnBeZNcRZjQTCIG2LRqU8_pSdA",
  "vary": "Origin, X-Origin",
  "content-type": "application/json; charset=UTF-8",
  "content-length": "215",
  "date": "Fri, 17 Jan 2020 10:05:37 GMT",
  "server": "UploadServer",
  "alt-svc": "quic=\":443\"; ma=2592000; v=\"46,43\",h3-Q050=\":443\"; ma=2592000,h3-Q049=\":443\"; ma=2592000,h3-Q048=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000",
  "connection": "close"
}
cleanup: Deleted 9b36f0f4-3e70-4b81-b8f5-5e412cd67a0b`
Stopped deamon

**Comment by inside83** [comment]
Weird thing is, if the torrent if a folder which contains files, it creates the folder on GDrive and it's empty.

**Comment by out386** [comment]
Does out/.constants.js have `IS_TEAM_DRIVE` set to true?

**Comment by inside83** [comment]
I just tried with both true and false and it's the same

**Comment by inside83** [comment]
Finally managed to get it fixed by coping
/aria-telegram-mirror-bot/src/.constants.js
from another server.
Difference being
`  
DRIVE_FILE_PRIVATE: {
    ENABLED: false,
  },
`
Not sure how or why but it works now.

**Comment by inside83** [comment]
Since I'm here I have to ask:
Can it be setup multiple time on the same server with multiple Telegram groups or just one per server?
Also, is it possible to set a name for a direct download file? For example: /mirror https://domain.com/video.mp4 | My awesome video

**Comment by out386** [comment]
> Not sure how or why but it works now. 

If it was set to true, but there wasn't a valid email address provided, that it would fail to set file permission after uploading.

>Can it be setup multiple time on the same server 

Yes. Use the `ARIA_PORT` variable in (constants)[https://github.com/out386/aria-telegram-mirror-bot/blob/master/README.md#constants-description], and use different ports for each bot. If you're using systemd, you'll have to copy the systemd file and change some variables. Also, don't forget to change the variables in `.constants.js`. 

>Also, is it possible to set a name for a direct download file?

No. I've had it planned for ages, never got around to it.

**Comment by inside83** [comment]
OMG it just happened again...with a 650+ GB torrent
Could it be due to a 750 GB daily limit or something?
