### ISSUE TITLE
What is the reason and solution for this? Happens several times.

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [out386/aria-telegram-mirror-bot#71]
Failed to upload ASHFALL.2019.1080p.FHDRip.H264.AAC-NonDRM.mp4 to Drive.Rate limit exceeded. User message: "These item(s) could not be shared because a rate limit was exceeded: ASHFALL.2019.1080p.FHDRip.H264.AAC-NonDRM.mp4"

**Comment by out386** [comment]
The message states exactly what happened. You uploaded too much to Drive in one day.

**Comment by ParveenBhadooOfficial** [comment]
no, this happens when we set drive to private. i checked.
i added a group email in private share with one email.
.constants.js.example
  DRIVE_FILE_PRIVATE: {
    ENABLED: true, //problem when set to true.
    EMAILS: ['someMail@googlegroups.com']
  },
