### ISSUE TITLE
credentials.py is not creating, im using team drive

### ISSUE THREAD

**Issue by tmdted** [out386/aria-telegram-mirror-bot#82]
After i enter the bot token in terminal, credentials.py is not being created(i checked root folder of server), it doesn't even show any error! I am using team drive now (first try), but this problem didn't happened when i used normal folders before. Is it something to do with my teamdrive? 

i set IS_TEAM_DRIVE: true, is there anything else? I even did with fresh client_secret.json

 i don't know what is stopping me to upload that 10mb.bin on teamdrive

![Untitled.png](https://i.postimg.cc/xdgJSzcd/Untitled.png)
![photo5078029384585160782.jpg](https://i.postimg.cc/QxC5bSYd/photo5078029384585160782.jpg)

**Comment by gotenksIN** [comment]
Does the upload complete though?
Also it's credentials.json not .py

**Comment by tmdted** [comment]
the error is solved when i mirror the file again.. credentials.json is created now.. but its unusual.. let me see until i finish this and if any more problems on this, i will tell.

**Comment by telegrammaster** [comment]
Solved this but re-mirroring the same file again after entering the token

**Comment by tmdted** [comment]
Solved this by mirroring the file again after entering the token
