### ISSUE TITLE
Download failed. Blacklisted URL.

### ISSUE THREAD

**Issue by iCesenberk** [out386/aria-telegram-mirror-bot#83]
![asdasda](https://user-images.githubusercontent.com/60349856/75087330-7755d280-5571-11ea-9466-34ead0d15f1a.PNG)

**Comment by out386** [comment]
Check `ARIA_FILTERED_DOMAINS` and `ARIA_FILTERED_FILENAMES` in your "src/.constants.js". Something in there is matching the link/filename you tried to mirror.

My guess is that one of them is set to `['']`, which will match everything.

**Comment by iCesenberk** [comment]
does it have to be filled in? I deleted the string because there was no name or link that I didn't want to filter
![asdasda](https://user-images.githubusercontent.com/60349856/75087626-758e0e00-5575-11ea-88e0-82233797d149.PNG)

**Comment by out386** [comment]
Remove the quotes.
