### ISSUE TITLE
Previous status message is not deleting! 

### ISSUE THREAD

**Issue by tmdted** [out386/aria-telegram-mirror-bot#84]
If we did not request /mirrorstatus within few minutes, previous status messages are not deleting and just sleeps after new update request is made.

        } else {
          var ttl = 3600000;
          msgTools.sendMessage(bot, msg, res.message, ttl, message => {
            dlManager.addStatus(message, res.message);
            setTimeout(() => {
              dlManager.deleteStatus(msg.chat.id);
            }, ttl);
            resolve();
          }, true);

ttl = 3600000 which means 1 hour, i made this change in in sendStatusMessage function of index.ts, thus these previous status messages are deleting fine after this 1 hour!! BUT it should be deleted after a new request is made 

And also I want the status message to be permanent without this timer, i tried that by setting this to false, but /mirrorstatus message we send is not being deleted after the statusupdate.
what to do? anyone help!

**Comment by out386** [comment]
If you want status messages sent by `/mirrorstatus` to not be auto-deleted, change line 95 of index.ts to `sendStatusMessage(msg, true);`

**Comment by tmdted** [comment]
@out386 I actually want it to be deleted after new request is made. But

the problem is, ttl is set to 1 hour, these previous status messages are deleting FINE after 1 hour!! BUT it should be deleted as soon as a new /mirrorstatus request is made, but it just sleeps! and not deleting!😥

**Comment by tmdted** [comment]
> If you want status messages sent by `/mirrorstatus` to not be auto-deleted, change line 95 of index.ts to `sendStatusMessage(msg, true);`

Fine i did it! But got another problem,

`Failed to delete message. Does the bot have message delete permissions for this chat? ETELEGRAM: 400 Bad Request: message to delete not found`

But it have all the permissions like auth_chat, admin rights to delete messages,etc..! Please help! @out386

**Comment by tmdted** [comment]
Solved! Thanx @out386

**Comment by out386** [comment]
What was the solution?

**Comment by tmdted** [comment]
After this, bot works like a charm
Everything else on index.ts is same except this mirrorstatus thing, I did the laststatus deletion here also,thus it runs twice, tho i don't know its necessary or not 🤷‍♂️!

And very important thing is, if we set `sendStatusMessage(msg, true);` , the /mirrorstatus message we send won't be deleted after the status message is sent. 

Thus i kept a 10 seconds deletion timer for it, so even if any lag also.. the status message will be printed within 10 seconds.. so no worries. But i need an alternate for this, i want the /mirrorstatus msg we send is to be deleted only after status update is send, no timers. But you can see i am not good at coding 😅 Suggest something efficient. @out386 

![Screenshot-20200225-003007-01.jpg](https://i.postimg.cc/fbs41mty/Screenshot-20200225-003007-01.jpg)
