### ISSUE TITLE
upload error 

### ISSUE THREAD

**Issue by leo1115** [out386/aria-telegram-mirror-bot#87]
Hello, i am facing this following error since yesterday (it was working fine before that) :

Failed to upload Gladiator (2000) Extended [1080p x265 HEVC].mkv to Drive. connect ENETUNREACH 2a00:1450:400e:804::200a:443 - Local (:::0)

What does this error mean & how can i resolve it. 

Thank you :)

**Comment by out386** [comment]
ENETUNREACH means it can't access Drive. Check firewall rules and the internet connection.

**Comment by leo1115** [comment]
Issue resolved after allowing connection through firewall. thanks <3.
