### ISSUE TITLE
get this error earlier was not there

### ISSUE THREAD

**Issue by destroyer19991** [out386/aria-telegram-mirror-bot#9]
undefined:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at fs.readFile (/home/bronx909/aria-telegram-mirror-bot/drive/drive-auth.js:16:20)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mirror-bot@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mirror-bot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-05T10_28_00_396Z-debug.log

**Comment by out386** [comment]
Your client_secret.json is messed up. Check the README again, and download that file again.

**Comment by destroyer19991** [comment]
let me check

**Comment by destroyer19991** [comment]
yup fixed thanks bro
