### ISSUE TITLE
The bot didn't auto update telegram messages

### ISSUE THREAD

**Issue by PengfeiXie** [out386/aria-telegram-mirror-bot#90]
I installed all the modules, and when I ran `npm start`, it showed normal output like this:
```
root@localhost:~/aria-telegram-mirror-bot# npm start

> mirror-bot@2.0.0 start /root/aria-telegram-mirror-bot
> NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js

A2C: Websocket opened. Bot ready.
```
I tried to send messages to the bot but it wasn't responding.
I checked the telegram API and found that the bot didn't do getupdates.
There's definitely nothing wrong with my `.constant.js` since I just re-installed the os and copied the same one which once successfully ran.  
What may be the problem?

**Comment by out386** [comment]
Try with a different test bot account, once. Sometimes (very rarely) Telegram bots stop responding for a couple days.

**Comment by PengfeiXie** [comment]
Yes！That works！
The previous bot was dead and I created a new bot and it came back to normal.
Thank you very much!!!
