### ISSUE TITLE
Issues while installing npm

### ISSUE THREAD

**Issue by basimaslamts** [out386/aria-telegram-mirror-bot#97]
npm WARN @typescript-eslint/eslint-plugin@1.13.0 requires a peer of eslint@^5.0.0 but none was installed.
npm WARN @typescript-eslint/parser@1.13.0 requires a peer of eslint@^5.0.0 but none was installed.
npm WARN mirror-bot@2.0.0 No repository field.

**Comment by A-LoneWolf** [comment]
npm install eslint@^5.0.0

npm install @typescript-eslint/eslint-plugin@1.13.0

npm install @typescript-eslint/parser@1.13.0

**Comment by basimaslamts** [comment]
Thanks. I got this:
npm install @typescript-eslint/parser@1.13.0
npm WARN mirror-bot@2.0.0 No repository field.

even with this it did work:)
